# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.9
fail_fast: true
minimum_pre_commit_version: 3.3.2

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.0
    hooks:
      - id: check-json5
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: prettier (JSON, Markdown & YAML)
        entry: prettier --write --list-different --ignore-unknown
        files: "\\.(json|md|yaml|yml)$"
  - repo: https://github.com/hadolint/hadolint # Hadolint must be installed locally
    rev: v2.12.0
    hooks:
      - id: hadolint
        name: hadolint
  - repo: local
    hooks:
      - id: forbid-yml-file
        name: no .yml extension
        entry: Yaml file must have the .yaml extension
        language: fail
        files: ".*\\.yml"
