name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - cuda-version: "8.0"
            ubuntu-version: "16.04"
            cuda-keyring-version: "1.0"
          - cuda-version: "9.0"
            ubuntu-version: "16.04"
            cuda-keyring-version: "1.0"
          - cuda-version: "9.1"
            ubuntu-version: "16.04"
            cuda-keyring-version: "1.0"
          - cuda-version: "9.2"
            ubuntu-version: "16.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "10.0"
            ubuntu-version: "18.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "10.1"
            ubuntu-version: "18.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "10.2"
            ubuntu-version: "18.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.0"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.1"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.2"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.3"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.4"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.5"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.6"
            ubuntu-version: "20.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.7"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "11.8"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.0"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.1"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.2"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.3"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.4"
            ubuntu-version: "22.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.5"
            ubuntu-version: "24.04"
            cuda-keyring-version: "1.1"
          - cuda-version: "12.6"
            ubuntu-version: "24.04"
            cuda-keyring-version: "1.1"
    steps:
      - name: sync-code
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker/setup-buildx-action@v3
      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/linux.Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          tags: ghcr.io/bendabir/cuda:${{ matrix.cuda-version }}
          labels: |
            maintainer="bendabir"
            org.opencontainers.image.source="https://github.com/bendabir/cuda"
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            CUDA_KEYRING_VERSION=${{ matrix.cuda-keyring-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
  clean:
    name: clean-images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: clean-images
        uses: actions/delete-package-versions@v5
        with:
          owner: bendabir
          package-name: cuda
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true
          min-versions-to-keep: 0 # all
