name: Build
on:
  push:
    branches: [main]
jobs:
  build:
    name: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        ubuntu-version: [22.04]
        cuda-version: [12.1]
        cuda-keyring-version: [1.1]
    steps:
      - name: sync-code
        uses: actions/checkout@v4
      - name: setup-docker
        uses: docker/setup-buildx-action@v3
      - name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: images/linux.Dockerfile
          platforms: linux/amd64
          pull: true
          push: true
          tags: ghcr.io/bendabir/cuda:${{ matrix.cuda-version }}
          labels: |
            maintainer="bendabir"
            org.opencontainers.image.source="https://github.com/bendabir/cuda"
          build-args: |
            UBUNTU_VERSION=${{ matrix.ubuntu-version }}
            CUDA_VERSION=${{ matrix.cuda-version }}
            CUDA_KEYRING_VERSION=${{ matrix.cuda-keyring-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
  clean:
    name: clean-images
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: clean-images
        uses: actions/delete-package-versions@v5
        with:
          owner: bendabir
          package-name: cuda
          package-type: container
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-only-untagged-versions: true
          min-versions-to-keep: 0 # all
